package de.danielhensel.palestrinizer;

public enum SoundForm {
	UNDETERMINED,
	NOTHING,
	SINGLENOTE,
	SINGLEINTERVALL,
	THIRDLESSCHORD,
	MAJOR,
	MINOR,
	DIMINISHED,
	AUGMENTED,
	DOMINANTSEVENTH,
	MAJORSEVENTH,
	HALFDIMINISHED,
	DOUBLEDIMINISHED,
	FOURTHCHORDS,
	FIFTHLESSCHORD;

}
